### ISSUE TITLE
Trim problem

### ISSUE THREAD

**Issue by thesourcerer8** [NetSPI/PEchecker#4]
I am getting this error, but then it seems to work correctly.
Method invocation failed because [System.String[]] doesn't contain a method named 'Trim'.
At Check-PESecurity.ps1:523 char:101
+         $DllCharacteristics = $NtHeader.OptionalHeader.DllCharacteristics.toString().Split(',').Trim <<<< ()
    + CategoryInfo          : InvalidOperation: (Trim:String) [], RuntimeExcep   tion
    + FullyQualifiedErrorId : MethodNotFound

**Comment by egru** [comment]
I fixed the code and it should work now.
